assert_lefthook_installed: true
pre-commit:
  parallel: true
  commands:
    prettier:
      run: pnpm exec prettier --check {staged_files} # We call prettier directly as package.json scripts feed . as path
    eslint:
      glob: '*.{js,cjs,mjs,ts,tsx,cts,mts,mts}'
      run: pnpm run lint:eslint {staged_files}
    markdownlint:
      glob: '*.{md}'
      run: pnpm run lint:markdownlint
    tsc:
      exclude:
        - 'eslint.config.mjs'
      glob: '*.{ts,tsx,cts,mts,mts}' # tsc-files does not support JS files
      run: pnpm exec tsc-files --noEmit {staged_files} # We run tsc-files because plain tsc ignores config when fed file list
